server:
  port: 8090
spring:
  application:
    name: api-gateway
  output:
    ansi:
      enabled: always  #console log color config
  cloud:
    gateway:
      routes:
        - id: helloService
          uri: lb://hello-service
          predicates:
            - Path=/hello-service/**
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
