server:
  port: 8761
eureka:
  client:
    healthcheck:
      enabled: true
    fetchRegistry: 'false'
    registerWithEureka: 'false'
  server:
    eviction-interval-timer-in-ms: 1000 # when instance stopped. remove eureka
spring:
  output:
    ansi:
      enabled: always  #console log color config